### ISSUE TITLE
pretrained models?

### ISSUE THREAD

**Issue by ghost** [IVRL/LELSD#3]
Hello,

Can you upload the pretrained models for testing?

Thanks!

**Comment by TheDevilWillBeBee** [comment]
Hi
I'm sorry for not getting back to you sooner. I've uploaded a set of pretrained models to Google Drive: 
[Google Drive Link](https://drive.google.com/file/d/1fRtkUL1BmUp3_YvM1BWUQltfgxK5HFKv/view?usp=sharing)
These latent space directions are optimized for a StyleGAN2 model trained on the FFHQ dataset and include directions for editing
- ears
- eyebrows
- eyeglass
- eyes
- hair
- mouth
- nose
- skin
- cloth
- background

You can test these models using the streamlit apps provided in the repo.
